## **설정**

In [1]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
## Setting
base_path = '/content/drive/MyDrive/CS2/'

## **CatBoost 01**
- Macro HS : 50-20
- Firm HS : 20-20

### **데이터 불러오기**

In [4]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '01_CatBoost_M5020_F2020')

result_2018_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [5]:
result_2018_catboost01.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020  0.012310  0.044013
1    PNW  2018-01-31   27991  0.020998 -0.053240
2    AAN  2018-01-31   10517  0.015810  0.026098
3    ABT  2018-01-31   20482  0.026383  0.094095
4    AMD  2018-01-31   61241  0.020432  0.336576

### **R-squared 값 구하기**

In [6]:
from sklearn.metrics import r2_score

y_true_2018_01 = result_2018_catboost01['true_ret']
y_pred_2018_01 = result_2018_catboost01['pred_ret']
r2_2018_01 = r2_score(y_true_2018_01, y_pred_2018_01)

y_true_2019_01 = result_2019_catboost01['true_ret']
y_pred_2019_01 = result_2019_catboost01['pred_ret']
r2_2019_01 = r2_score(y_true_2019_01, y_pred_2019_01)

y_true_2020_01 = result_2020_catboost01['true_ret']
y_pred_2020_01 = result_2020_catboost01['pred_ret']
r2_2020_01 = r2_score(y_true_2020_01, y_pred_2020_01)

y_true_2021_01 = result_2021_catboost01['true_ret']
y_pred_2021_01 = result_2021_catboost01['pred_ret']
r2_2021_01 = r2_score(y_true_2021_01, y_pred_2021_01)

summary_r2_01 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_01, r2_2019_01, r2_2020_01, r2_2021_01]})
summary_r2_01['HS'] = 'M5020_F2020'
display(summary_r2_01)

   Year  R-squared           HS
0  2018  -0.094493  M5020_F2020
1  2019  -0.059531  M5020_F2020
2  2020   0.000113  M5020_F2020
3  2021  -0.022639  M5020_F2020

## **CatBoost 02**
- Macro HS : 50-20
- Firm HS : 50-20

### **데이터 불러오기**

In [7]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '02_CatBoost_M5020_F5020')

result_2018_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [8]:
result_2018_catboost02.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020  0.009797  0.044013
1    PNW  2018-01-31   27991  0.002691 -0.053240
2    AAN  2018-01-31   10517  0.019565  0.026098
3    ABT  2018-01-31   20482  0.001140  0.094095
4    AMD  2018-01-31   61241  0.060669  0.336576

### **R-squared 값 구하기**

In [9]:
from sklearn.metrics import r2_score

y_true_2018_02 = result_2018_catboost02['true_ret']
y_pred_2018_02 = result_2018_catboost02['pred_ret']
r2_2018_02 = r2_score(y_true_2018_02, y_pred_2018_02)

y_true_2019_02 = result_2019_catboost02['true_ret']
y_pred_2019_02 = result_2019_catboost02['pred_ret']
r2_2019_02 = r2_score(y_true_2019_02, y_pred_2019_02)

y_true_2020_02 = result_2020_catboost02['true_ret']
y_pred_2020_02 = result_2020_catboost02['pred_ret']
r2_2020_02 = r2_score(y_true_2020_02, y_pred_2020_02)

y_true_2021_02 = result_2021_catboost02['true_ret']
y_pred_2021_02 = result_2021_catboost02['pred_ret']
r2_2021_02 = r2_score(y_true_2021_02, y_pred_2021_02)

summary_r2_02 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_02, r2_2019_02, r2_2020_02, r2_2021_02]})
summary_r2_02['HS'] = 'M5020_F5020'
display(summary_r2_02)

   Year  R-squared           HS
0  2018  -0.040131  M5020_F5020
1  2019  -0.034481  M5020_F5020
2  2020  -0.110847  M5020_F5020
3  2021  -0.014536  M5020_F5020

## **CatBoost 03**
- Macro HS : 20-10
- Firm HS : 20-20

### **데이터 불러오기**

In [10]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '03_CatBoost_M2010_F2020')

result_2018_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [11]:
result_2018_catboost03.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020  0.047667  0.044013
1    PNW  2018-01-31   27991  0.012774 -0.053240
2    AAN  2018-01-31   10517  0.029785  0.026098
3    ABT  2018-01-31   20482  0.036860  0.094095
4    AMD  2018-01-31   61241 -0.015452  0.336576

### **R-squared 값 구하기**

In [12]:
from sklearn.metrics import r2_score

y_true_2018_03 = result_2018_catboost03['true_ret']
y_pred_2018_03 = result_2018_catboost03['pred_ret']
r2_2018_03 = r2_score(y_true_2018_03, y_pred_2018_03)

y_true_2019_03 = result_2019_catboost03['true_ret']
y_pred_2019_03 = result_2019_catboost03['pred_ret']
r2_2019_03 = r2_score(y_true_2019_03, y_pred_2019_03)

y_true_2020_03 = result_2020_catboost03['true_ret']
y_pred_2020_03 = result_2020_catboost03['pred_ret']
r2_2020_03 = r2_score(y_true_2020_03, y_pred_2020_03)

y_true_2021_03 = result_2021_catboost03['true_ret']
y_pred_2021_03 = result_2021_catboost03['pred_ret']
r2_2021_03 = r2_score(y_true_2021_03, y_pred_2021_03)

summary_r2_03 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_03, r2_2019_03, r2_2020_03, r2_2021_03]})
summary_r2_03['HS'] = 'M2010_F2020'
display(summary_r2_03)

   Year  R-squared           HS
0  2018  -0.300071  M2010_F2020
1  2019  -0.307109  M2010_F2020
2  2020  -0.052171  M2010_F2020
3  2021  -0.037467  M2010_F2020

## **CatBoost 04**
- Macro HS : 50-10
- Firm HS : 20-20

### **데이터 불러오기**

In [13]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '04_CatBoost_M5010_F2020')

result_2018_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [14]:
result_2018_catboost04.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020 -0.051838  0.044013
1    PNW  2018-01-31   27991 -0.025387 -0.053240
2    AAN  2018-01-31   10517 -0.009836  0.026098
3    ABT  2018-01-31   20482 -0.057399  0.094095
4    AMD  2018-01-31   61241  0.006676  0.336576

### **R-squared 값 구하기**

In [15]:
from sklearn.metrics import r2_score

y_true_2018_04 = result_2018_catboost04['true_ret']
y_pred_2018_04 = result_2018_catboost04['pred_ret']
r2_2018_04 = r2_score(y_true_2018_04, y_pred_2018_04)

y_true_2019_04 = result_2019_catboost04['true_ret']
y_pred_2019_04 = result_2019_catboost04['pred_ret']
r2_2019_04 = r2_score(y_true_2019_04, y_pred_2019_04)

y_true_2020_04 = result_2020_catboost04['true_ret']
y_pred_2020_04 = result_2020_catboost04['pred_ret']
r2_2020_04 = r2_score(y_true_2020_04, y_pred_2020_04)

y_true_2021_04 = result_2021_catboost04['true_ret']
y_pred_2021_04 = result_2021_catboost04['pred_ret']
r2_2021_04 = r2_score(y_true_2021_04, y_pred_2021_04)

summary_r2_04 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_04, r2_2019_04, r2_2020_04, r2_2021_04]})
summary_r2_04['HS'] = 'M5010_F2020'
display(summary_r2_04)

   Year  R-squared           HS
0  2018  -0.293657  M5010_F2020
1  2019  -0.050022  M5010_F2020
2  2020  -0.051810  M5010_F2020
3  2021  -0.005884  M5010_F2020

## **비교**

In [16]:
combined_r2_summary = pd.concat([summary_r2_01, summary_r2_02, summary_r2_03, summary_r2_04], ignore_index=True)
display(combined_r2_summary)

    Year  R-squared           HS
0   2018  -0.094493  M5020_F2020
1   2019  -0.059531  M5020_F2020
2   2020   0.000113  M5020_F2020
3   2021  -0.022639  M5020_F2020
4   2018  -0.040131  M5020_F5020
5   2019  -0.034481  M5020_F5020
6   2020  -0.110847  M5020_F5020
7   2021  -0.014536  M5020_F5020
8   2018  -0.300071  M2010_F2020
9   2019  -0.307109  M2010_F2020
10  2020  -0.052171  M2010_F2020
11  2021  -0.037467  M2010_F2020
12  2018  -0.293657  M5010_F2020
13  2019  -0.050022  M5010_F2020
14  2020  -0.051810  M5010_F2020
15  2021  -0.005884  M5010_F2020

In [17]:
pivoted_r2_summary = combined_r2_summary.pivot_table(index='HS', columns='Year', values='R-squared')
display(pivoted_r2_summary)

Year             2018      2019      2020      2021
HS
M2010_F2020 -0.300071 -0.307109 -0.052171 -0.037467
M5010_F2020 -0.293657 -0.050022 -0.051810 -0.005884
M5020_F2020 -0.094493 -0.059531  0.000113 -0.022639
M5020_F5020 -0.040131 -0.034481 -0.110847 -0.014536

In [20]:
pivoted_r2_summary['Row_Mean'] = pivoted_r2_summary.mean(axis=1)
display(pivoted_r2_summary)

Year             2018      2019      2020      2021  Row_Mean
HS
M2010_F2020 -0.300071 -0.307109 -0.052171 -0.037467 -0.174204
M5010_F2020 -0.293657 -0.050022 -0.051810 -0.005884 -0.100343
M5020_F2020 -0.094493 -0.059531  0.000113 -0.022639 -0.044138
M5020_F5020 -0.040131 -0.034481 -0.110847 -0.014536 -0.049999