## **설정**

In [ ]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
## Setting
base_path = '/content/drive/MyDrive/CS/'

## **CatBoost 01**
- Macro HS : 50-20
- Firm HS : 20-20

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '01_CatBoost_M5020_F2020')

result_2018_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost01 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_catboost01.head()

   Unnamed: 0 ticker        date  pred_ret  true_ret  permno
0           0    AAL  2018-01-31  0.023058  0.044013   21020
1           1    PNW  2018-01-31  0.015580 -0.053240   27991
2           2    AAN  2018-01-31  0.018414  0.026098   10517
3           3    ABT  2018-01-31  0.017164  0.094095   20482
4           4    AMD  2018-01-31  0.022712  0.336576   61241

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018_01 = result_2018_catboost01['true_ret']
y_pred_2018_01 = result_2018_catboost01['pred_ret']
r2_2018_01 = r2_score(y_true_2018_01, y_pred_2018_01)

y_true_2019_01 = result_2019_catboost01['true_ret']
y_pred_2019_01 = result_2019_catboost01['pred_ret']
r2_2019_01 = r2_score(y_true_2019_01, y_pred_2019_01)

y_true_2020_01 = result_2020_catboost01['true_ret']
y_pred_2020_01 = result_2020_catboost01['pred_ret']
r2_2020_01 = r2_score(y_true_2020_01, y_pred_2020_01)

y_true_2021_01 = result_2021_catboost01['true_ret']
y_pred_2021_01 = result_2021_catboost01['pred_ret']
r2_2021_01 = r2_score(y_true_2021_01, y_pred_2021_01)

summary_r2_01 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_01, r2_2019_01, r2_2020_01, r2_2021_01]})
summary_r2_01['HS'] = 'M5020_F2020'
display(summary_r2_01)

   Year  R-squared           HS
0  2018  -0.030180  M5020_F2020
1  2019  -0.091090  M5020_F2020
2  2020  -0.158455  M5020_F2020
3  2021   0.011832  M5020_F2020

## **CatBoost 02**
- Macro HS : 50-20
- Firm HS : 50-20

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '02_CatBoost_M5020_F5020')

result_2018_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost02 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_catboost02.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020  0.024992  0.044013
1    PNW  2018-01-31   27991  0.023063 -0.053240
2    AAN  2018-01-31   10517  0.025741  0.026098
3    ABT  2018-01-31   20482  0.016617  0.094095
4    AMD  2018-01-31   61241  0.046442  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018_02 = result_2018_catboost02['true_ret']
y_pred_2018_02 = result_2018_catboost02['pred_ret']
r2_2018_02 = r2_score(y_true_2018_02, y_pred_2018_02)

y_true_2019_02 = result_2019_catboost02['true_ret']
y_pred_2019_02 = result_2019_catboost02['pred_ret']
r2_2019_02 = r2_score(y_true_2019_02, y_pred_2019_02)

y_true_2020_02 = result_2020_catboost02['true_ret']
y_pred_2020_02 = result_2020_catboost02['pred_ret']
r2_2020_02 = r2_score(y_true_2020_02, y_pred_2020_02)

y_true_2021_02 = result_2021_catboost02['true_ret']
y_pred_2021_02 = result_2021_catboost02['pred_ret']
r2_2021_02 = r2_score(y_true_2021_02, y_pred_2021_02)

summary_r2_02 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_02, r2_2019_02, r2_2020_02, r2_2021_02]})
summary_r2_02['HS'] = 'M5020_F5020'
display(summary_r2_02)

   Year  R-squared           HS
0  2018  -0.111979  M5020_F5020
1  2019  -0.050148  M5020_F5020
2  2020  -0.064048  M5020_F5020
3  2021  -0.009251  M5020_F5020

## **CatBoost 03**
- Macro HS : 20-10
- Firm HS : 20-20

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '03_CatBoost_M2010_F2020')

result_2018_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost03 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_catboost03.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020 -0.001045  0.044013
1    PNW  2018-01-31   27991  0.023113 -0.053240
2    AAN  2018-01-31   10517  0.014096  0.026098
3    ABT  2018-01-31   20482  0.014265  0.094095
4    AMD  2018-01-31   61241  0.013793  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018_03 = result_2018_catboost03['true_ret']
y_pred_2018_03 = result_2018_catboost03['pred_ret']
r2_2018_03 = r2_score(y_true_2018_03, y_pred_2018_03)

y_true_2019_03 = result_2019_catboost03['true_ret']
y_pred_2019_03 = result_2019_catboost03['pred_ret']
r2_2019_03 = r2_score(y_true_2019_03, y_pred_2019_03)

y_true_2020_03 = result_2020_catboost03['true_ret']
y_pred_2020_03 = result_2020_catboost03['pred_ret']
r2_2020_03 = r2_score(y_true_2020_03, y_pred_2020_03)

y_true_2021_03 = result_2021_catboost03['true_ret']
y_pred_2021_03 = result_2021_catboost03['pred_ret']
r2_2021_03 = r2_score(y_true_2021_03, y_pred_2021_03)

summary_r2_03 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_03, r2_2019_03, r2_2020_03, r2_2021_03]})
summary_r2_03['HS'] = 'M2010_F2020'
display(summary_r2_03)

   Year  R-squared           HS
0  2018  -0.060698  M2010_F2020
1  2019  -0.056234  M2010_F2020
2  2020  -0.001451  M2010_F2020
3  2021   0.011707  M2010_F2020

## **CatBoost 04**
- Macro HS : 50-10
- Firm HS : 20-20

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', '04_CatBoost_M5010_F2020')

result_2018_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost04 = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_catboost04.head()

  ticker        date  permno  pred_ret  true_ret
0    AAL  2018-01-31   21020  0.010381  0.044013
1    PNW  2018-01-31   27991  0.009898 -0.053240
2    AAN  2018-01-31   10517  0.021079  0.026098
3    ABT  2018-01-31   20482  0.016744  0.094095
4    AMD  2018-01-31   61241  0.030337  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018_04 = result_2018_catboost04['true_ret']
y_pred_2018_04 = result_2018_catboost04['pred_ret']
r2_2018_04 = r2_score(y_true_2018_04, y_pred_2018_04)

y_true_2019_04 = result_2019_catboost04['true_ret']
y_pred_2019_04 = result_2019_catboost04['pred_ret']
r2_2019_04 = r2_score(y_true_2019_04, y_pred_2019_04)

y_true_2020_04 = result_2020_catboost04['true_ret']
y_pred_2020_04 = result_2020_catboost04['pred_ret']
r2_2020_04 = r2_score(y_true_2020_04, y_pred_2020_04)

y_true_2021_04 = result_2021_catboost04['true_ret']
y_pred_2021_04 = result_2021_catboost04['pred_ret']
r2_2021_04 = r2_score(y_true_2021_04, y_pred_2021_04)

summary_r2_04 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018_04, r2_2019_04, r2_2020_04, r2_2021_04]})
summary_r2_04['HS'] = 'M5010_F2020'
display(summary_r2_04)

   Year  R-squared           HS
0  2018  -0.039500  M5010_F2020
1  2019  -0.317546  M5010_F2020
2  2020  -0.420242  M5010_F2020
3  2021  -0.016380  M5010_F2020

## **비교**

In [ ]:
combined_r2_summary = pd.concat([summary_r2_01, summary_r2_02, summary_r2_03, summary_r2_04], ignore_index=True)
display(combined_r2_summary)

    Year  R-squared           HS
0   2018  -0.030180  M5020_F2020
1   2019  -0.091090  M5020_F2020
2   2020  -0.158455  M5020_F2020
3   2021   0.011832  M5020_F2020
4   2018  -0.111979  M5020_F5020
5   2019  -0.050148  M5020_F5020
6   2020  -0.064048  M5020_F5020
7   2021  -0.009251  M5020_F5020
8   2018  -0.060698  M2010_F2020
9   2019  -0.056234  M2010_F2020
10  2020  -0.001451  M2010_F2020
11  2021   0.011707  M2010_F2020
12  2018  -0.039500  M5010_F2020
13  2019  -0.317546  M5010_F2020
14  2020  -0.420242  M5010_F2020
15  2021  -0.016380  M5010_F2020

In [ ]:
pivoted_r2_summary = combined_r2_summary.pivot_table(index='HS', columns='Year', values='R-squared')
display(pivoted_r2_summary)

Year             2018      2019      2020      2021
HS
M2010_F2020 -0.060698 -0.056234 -0.001451  0.011707
M5010_F2020 -0.039500 -0.317546 -0.420242 -0.016380
M5020_F2020 -0.030180 -0.091090 -0.158455  0.011832
M5020_F5020 -0.111979 -0.050148 -0.064048 -0.009251