- Macro HS : 50-20
- Firm HS : 20-20

## **설정**

In [ ]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
## Setting
base_path = '/content/drive/MyDrive/CS/'

## **CatBoost**

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', 'CatBoost')

result_2018_catboost = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_catboost = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_catboost = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_catboost = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_catboost.head()

  ticker        date  pred_ret  true_ret
0    AAL  2018-01-31  0.023058  0.044013
1    PNW  2018-01-31  0.015580 -0.053240
2    AAN  2018-01-31  0.018414  0.026098
3    ABT  2018-01-31  0.017164  0.094095
4    AMD  2018-01-31  0.022712  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018 = result_2018_catboost['true_ret']
y_pred_2018 = result_2018_catboost['pred_ret']
r2_2018 = r2_score(y_true_2018, y_pred_2018)

y_true_2019 = result_2019_catboost['true_ret']
y_pred_2019 = result_2019_catboost['pred_ret']
r2_2019 = r2_score(y_true_2019, y_pred_2019)

y_true_2020 = result_2020_catboost['true_ret']
y_pred_2020 = result_2020_catboost['pred_ret']
r2_2020 = r2_score(y_true_2020, y_pred_2020)

y_true_2021 = result_2021_catboost['true_ret']
y_pred_2021 = result_2021_catboost['pred_ret']
r2_2021 = r2_score(y_true_2021, y_pred_2021)

summary_r2 = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018, r2_2019, r2_2020, r2_2021]})
summary_r2['model'] = 'CatBoost'
display(summary_r2)

   Year  R-squared     model
0  2018  -0.030180  CatBoost
1  2019  -0.091090  CatBoost
2  2020  -0.158455  CatBoost
3  2021   0.011832  CatBoost

## **XGBoost**

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', 'XGB')

result_2018_xgb = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_xgb = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_xgb = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_xgb = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_xgb.head()

  ticker        date  pred_ret  true_ret
0    AAL  2018-01-31  0.003414  0.044013
1    PNW  2018-01-31  0.008319 -0.053240
2    AAN  2018-01-31 -0.003324  0.026098
3    ABT  2018-01-31  0.006443  0.094095
4    AMD  2018-01-31 -0.025708  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018 = result_2018_xgb['true_ret']
y_pred_2018 = result_2018_xgb['pred_ret']
r2_2018 = r2_score(y_true_2018, y_pred_2018)

y_true_2019 = result_2019_xgb['true_ret']
y_pred_2019 = result_2019_xgb['pred_ret']
r2_2019 = r2_score(y_true_2019, y_pred_2019)

y_true_2020 = result_2020_xgb['true_ret']
y_pred_2020 = result_2020_xgb['pred_ret']
r2_2020 = r2_score(y_true_2020, y_pred_2020)

y_true_2021 = result_2021_xgb['true_ret']
y_pred_2021 = result_2021_xgb['pred_ret']
r2_2021 = r2_score(y_true_2021, y_pred_2021)

summary_r2_xgb = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018, r2_2019, r2_2020, r2_2021]})
summary_r2_xgb['model'] = 'XGBoost'
display(summary_r2_xgb)

   Year  R-squared    model
0  2018  -0.130661  XGBoost
1  2019  -0.708061  XGBoost
2  2020  -0.115522  XGBoost
3  2021  -0.158655  XGBoost

## **TabNet**

### **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'PredData', 'TabNet')

result_2018_tabnet = pd.read_csv(os.path.join(file_path, 'result_2018.csv'))
result_2019_tabnet = pd.read_csv(os.path.join(file_path, 'result_2019.csv'))
result_2020_tabnet = pd.read_csv(os.path.join(file_path, 'result_2020.csv'))
result_2021_tabnet = pd.read_csv(os.path.join(file_path, 'result_2021.csv'))

In [ ]:
result_2018_tabnet.head()

  ticker        date  pred_ret  true_ret
0    AAL  2018-01-31  0.012964  0.044013
1    PNW  2018-01-31  0.012645 -0.053240
2    AAN  2018-01-31  0.012911  0.026098
3    ABT  2018-01-31  0.012463  0.094095
4    AMD  2018-01-31  0.013991  0.336576

### **R-squared 값 구하기**

In [ ]:
from sklearn.metrics import r2_score

y_true_2018 = result_2018_tabnet['true_ret']
y_pred_2018 = result_2018_tabnet['pred_ret']
r2_2018 = r2_score(y_true_2018, y_pred_2018)

y_true_2019 = result_2019_tabnet['true_ret']
y_pred_2019 = result_2019_tabnet['pred_ret']
r2_2019 = r2_score(y_true_2019, y_pred_2019)

y_true_2020 = result_2020_tabnet['true_ret']
y_pred_2020 = result_2020_tabnet['pred_ret']
r2_2020 = r2_score(y_true_2020, y_pred_2020)

y_true_2021 = result_2021_tabnet['true_ret']
y_pred_2021 = result_2021_tabnet['pred_ret']
r2_2021 = r2_score(y_true_2021, y_pred_2021)

summary_r2_tabnet = pd.DataFrame({'Year': [2018, 2019, 2020, 2021], 'R-squared': [r2_2018, r2_2019, r2_2020, r2_2021]})
summary_r2_tabnet['model'] = 'Tabnet'
display(summary_r2_tabnet)

   Year  R-squared   model
0  2018  -0.261040  Tabnet
1  2019  -0.770588  Tabnet
2  2020  -0.621838  Tabnet
3  2021  -0.015176  Tabnet

## **비교**

In [ ]:
combined_r2_summary = pd.concat([summary_r2, summary_r2_xgb, summary_r2_tabnet], ignore_index=True)
display(combined_r2_summary)

    Year  R-squared     model
0   2018  -0.030180  CatBoost
1   2019  -0.091090  CatBoost
2   2020  -0.158455  CatBoost
3   2021   0.011832  CatBoost
4   2018  -0.130661   XGBoost
5   2019  -0.708061   XGBoost
6   2020  -0.115522   XGBoost
7   2021  -0.158655   XGBoost
8   2018  -0.261040    Tabnet
9   2019  -0.770588    Tabnet
10  2020  -0.621838    Tabnet
11  2021  -0.015176    Tabnet

In [ ]:
pivoted_r2_summary = combined_r2_summary.pivot_table(index='model', columns='Year', values='R-squared')
display(pivoted_r2_summary)

Year          2018      2019      2020      2021
model
CatBoost -0.030180 -0.091090 -0.158455  0.011832
Tabnet   -0.261040 -0.770588 -0.621838 -0.015176
XGBoost  -0.130661 -0.708061 -0.115522 -0.158655